from config import APP_NAME, APP_VERSION, REPORT_VERSION
from models.patient import Patient
from datetime import datetime

def generate_report(patient: Patient, analysis_id: str) -> str:
    return f"""# {APP_NAME}

**System Version:** {APP_VERSION}  
**Report Version:** {REPORT_VERSION}

## Case Identification

| Field | Value |
|---|---|
| MRN | {patient.mrn} |
| Analysis ID | {analysis_id} |
| Visit No. | 1 |
| Visit Date | {datetime.now():%Y-%m-%d} |
| Visit Time | {datetime.now():%H:%M} |

## Patient Information

| Field | Value |
|---|---|
| Patient Name | {patient.name} |
| Species | {patient.species} |
| Breed | {patient.breed} |
| Age | {patient.age} |
| Sex | {patient.sex} |
| Body Weight | {patient.weight:.2f} kg |

## Clinical Analysis

### Critical Alerts
No laboratory data entered yet.

### Problem List
Not yet assessed.

### Differential Diagnosis
Not yet assessed.

### Diagnostic Plan
Not yet assessed.

### Treatment Considerations
Clinical decision support only; veterinarian review required.

### Monitoring Plan
Not yet assessed.

### SOAP – Assessment
Not yet assessed.

---
*Generated by VetLabAI Vet-CDSS. This report does not replace professional veterinary judgment.*
"""
